### ISSUE TITLE
Transport connection sharing

### ISSUE THREAD

**Issue by SzymonPobiega** [NServiceBusExtensions/NServiceBus.Attachments#5]
Ended up going with `UseTransportConnectivity()`

----

I have hard time trying add the transport connection sharing. The main issue is the user-facing API.

Currently, the user is expected to provide a connection builder. This builder is used to open connection when sending and receiving messages as well as when when doing attachment store cleanup.

When using a SQL transport in the native transaction mode the transport connection/transaction can be used to load/store the attachment. It cannot be used for the cleanup though.

At first I thought that I'll just check if there is connection/transaction in the context and if so, use it. The cleanup would be run with the connection provided by the user. After thinking about it for some time I don't think this is a good approach. One of the main reasons is that I can't check if the transport connection and the user-provided connection have same connection string unless I actually create the user-provided connection but this defeats the purpose of sharing.

I think a better API would be explicit e.g.

```
var attachments = config.EnableAttachments();
attachments.UseTransportConnection();
//or
attachments.UseConnection(() => new SqlConnection());

//and make the clean-up connection a separate API
attachments.RunCleanup(() => new SqlConnection());
```

This way we we minimize the chances that user will make a mistake.

**Comment by SimonCropp** [comment]
happy with the explicit api proposal

**Comment by SzymonPobiega** [comment]
I didn't forget about this. I just have little time recently :-(

**Comment by SimonCropp** [comment]
@SzymonPobiega still interested in this?
