### ISSUE TITLE
Consistency guarantees & cleanup

### ISSUE THREAD

**Issue by SzymonPobiega** [NServiceBusExtensions/NServiceBus.Attachments#6]
When raising the issue about the connection sharing (#5 ) I started thinking about the reasons why we would want to share the connection. 

When sharing a connection the attachments would be added atomically with sending a message. Then, when receiving a message there could be a behavior that deletes the attachments for that message within the message receive transaction. In this case no cleanup is needed and the lifetime of the attachment is strictly bound to the lifetime of a message row in the SQL Server transport.

Let's look at the non-shared example. In this case we can't delete the attachments when processing a message because the very last thing in NServiceBus pipeline is committing the receive transaction. If we had deleted the attachments and the receive transaction commit failed we would be in trouble as the next time the message would be received the attachment would be gone.

We can't really execute any code *after* the receive transaction is committed because there is no hook for that. What we can do, though, is we can send a message "Remove attachment XYZ" as part of the message receive transaction. This would work in transports that support `SendsAtomicWithReceive`. The most notable transport that does *not* support it is RabbitMQ. In native RabbitMQ we would be out of luck -- we can't reliably execute code after a message has been processed. We can, though, if we use the outbox. The "Remove attachment XYZ" message would be added to the outbox and dispatched. Then a behavior very early in the pipeline would detect it and removed the redundant attachment.

On the sending side the sharing of connection guarantees that the attachment information is stored atomically with the message. If we don't share we need to store the attachment before we send the associated message. We can fail in two places:
 * Between storing attachment and sending a message: in this case we will overwrite the attachment when re-processing the incoming message
 * After sending the message. If we use deterministic message IDs we will overwrite the attachment and send another message. If not, we will send a brand new pair of attachment and ID.

In the former case, if the processing endpoint happened to execute the cleanup action after the attachment is overwritten but before it processes the duplicate message, it will get a message without the associated attachment.

**Comment by SimonCropp** [comment]
i had considered the "cleanup on receive". i was planning on only targeting "send" messages. ie not publish. that way there should be no shared resource contention. does that sound safe?

also note that if an attachments succeeds on writing, but the message sends fails, this is not a problem since those attachments will have the guid of the non-sent message. hence when a retry occurs and a new message+attachments is send they will have a new guid.

**Comment by SzymonPobiega** [comment]
@SimonCropp thinking about it now I think that we can remove the attachments in a behavior in `TransportReceive` pipe. We can allow users to opt-out from this behavior if they wish to control the deletion of attachments manually.

### SQL Server transport native transactions

In this mode we can hook to the SQL Server transport connection and remove the attachment atomically with removing the message

### Any DTC-enabled transport

In this mode we can open a new connection remove the attachment as part of a distributed transaction

### Any Outbox-enabled setup

In this mode we can open a new connection remove the attachment. Because we would run the behavior in transport receive pipe, after the outbox logica completed, we can be sure that the business data is safely stored.

### At-least-once

In this mode the user has full control over the business logic idempotency. But still in the transport receive pipeline we can safely remove the attachment. When the message comes up again the code in the handler will figure out that the message is a duplicate and will skip the part that uses the attachment.

**Comment by SimonCropp** [comment]
@SzymonPobiega sounds good. want to submit a PR?
