### ISSUE TITLE
Sending multiple attachments while using the sqlconnectionFactory throws exceptions

### ISSUE THREAD

**Issue by trollshaw** [NServiceBusExtensions/NServiceBus.Attachments#97]
I have trouble sending multiple attachments. We use MSMQ for transport and want to use an sqlserver for the attachments. 

When sending the attachments an exception is thrown. 
```InvalidOperationException: The connection does not support MultipleActiveResultSets```

With MultipleActiveResultSets=True in the connectionstring this exception is solved, but when more than 7 another exception is thrown.
```System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.```

My guess is the origin of the exceptions is in SendBehavior.cs ProcessOutgoing(...) where multiple (running) task are collected with Select(..) and Add(...) and passing the same connection.
```
        var tasks = outgoingAttachments.Inner
            .Select(pair => ProcessAttachment(timeToBeReceived, connection, transaction, context.MessageId, pair.Value, pair.Key))
            .ToList();
```

**Comment by SimonCropp** [comment]
Can you share a failing unit test as a github pull request

**Comment by trollshaw** [comment]
I'll try to formulate one.

**Comment by SimonCropp** [comment]
@trollshaw BTW you should be a backer to be using this project https://github.com/NServiceBusExtensions/Home

**Comment by SimonCropp** [comment]
i added a test for multiple streams. https://github.com/NServiceBusExtensions/NServiceBus.Attachments/commit/56a7f11e43ff67db258e67cf606667bf9f956e41

still cant repro your issue. since i cant repo it, i will close for now. Happy to re-open when you can supply a repro.
